[options]
http_port = 1515
admin_passwd = 
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = root
db_name = Naman_Pack_World
addons_path = D:\odoo-19.0\odoo-19.0\addons, D:\Naman_Pack_World
logfile = D:\Naman_Pack_World\odoo.log
log_level = info
dev_mode = reload 
workers = 0
xmlrpc_interface = 0.0.0.0
netrpc_interface = 0.0.0.0
xmlrpc_port = 1515
netrpc_port = 1515
# python odoo-bin -c odoo.conf
# python D:\odoo-19.0\odoo-19.0\odoo-bin -c D:\Naman_Pack_World\odoo.conf